export const MESSAGE_TYPES = {
  START_PAGE_TRANSLATION: "START_PAGE_TRANSLATION",
  SUBMIT_SEGMENTS_BATCH: "SUBMIT_SEGMENTS_BATCH",
  BATCH_RESULT: "BATCH_RESULT",
  TRANSLATION_PROGRESS: "TRANSLATION_PROGRESS",
  TRANSLATION_ERROR: "TRANSLATION_ERROR",
} as const;
